const books = [
  {
    id: '1',
    name: 'إلى الله',
    image: require('../assets/images/books/26.jpg'),
    price: '180 EPG',
    rating: 3.2,
    liked: true,
  },
  {
    id: '2',
    name: 'استراحة نفسية',
    image: require('../assets/images/books/27.jpg'),
    price: '190 EPG',
    rating: 4.1,
    liked: true,
  },
  {
    id: '3',
    name: 'يوتوبيا',
    image: require('../assets/images/books/30.jpg'),
    price: '100 EPG',
    rating: 4.3,
    liked: true,
  },
  {
    id: '4',
    name: 'إلى ما لا نهاية',
    image: require('../assets/images/books/50.jpg'),
    price: '90 EPG',
    rating: 3.1,
    liked: true,
  },
  {
    id: '5',
    name: 'ما رواه البحر',
    image: require('../assets/images/books/51.jpg'),
    price: '90 EPG',
    rating: 2.9,
    liked: true,
  },
  {
    id: '6',
    name: 'ماذا لو',
    image: require('../assets/images/books/54.jpg'),
    price: '120 EPG',
    rating: 2.1,
    liked: true,
  },
  {
    id: '7',
    name: 'في قلبي أنثى عبرية',
    image: require('../assets/images/books/73.jpg'),
    price: '90 EPG',
    rating: 4.5,
    liked: true,
  },
  {
    id: '8',
    name: 'غربة الياسمين',
    image: require('../assets/images/books/78.jpg'),
    price: '90 EPG',
    rating: 4.3,
    liked: true,
  },
  {
    id: '9',
    name: 'أن تبقى',
    image: require('../assets/images/books/77.jpg'),
    price: '90 EPG',
    rating: 3.9,
    liked: true,
  },
  {
    id: '10',
    name: 'أين المفر',
    image: require('../assets/images/books/75.jpg'),
    price: '95 EPG',
    rating: 2.9,
    liked: true,
  },
  {
    id: '11',
    name: 'أرني أنظر إليك',
    image: require('../assets/images/books/74.png'),
    price: '100 EPG',
    rating: 4.7,
    liked: true,
  },
  {
    id: '12',
    name: 'ياسمين العودة',
    image: require('../assets/images/books/76.jpg'),
    price: '120 EPG',
    rating: 4.9,
    liked: true,
  },
  {
    id: '13',
    name: 'الزعفرانة',
    image: require('../assets/images/books/49.jpg'),
    price: '150 EPG',
    rating: 4.3,
    liked: true,
  },
  {
    id: '14',
    name: 'Finding Freedom',
    image: require('../assets/images/books/5.jpg'),
    price: '200 EPG',
    rating: 4.2,
    liked: true,
  },
  {
    id: '15',
    name: 'REMINDERS OF HIM',
    image: require('../assets/images/books/18.jpg'),
    price: '200 EPG',
    rating: 4.6,
    liked: true,
  },
  {
    id: '16',
    name: 'IT STARTS WITH US',
    image: require('../assets/images/books/71.jpg'),
    price: '200 EPG',
    rating: 4.5,
    liked: true,
  },
  {
    id: '17',
    name: 'IT ENDS WITH US',
    image: require('../assets/images/books/72.jpg'),
    price: '200 EPG',
    rating: 4.1,
    liked: true,
  },
];
export default books;
